# Generated by Django 4.1.7 on 2023-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phonenumber', models.CharField(default=None, max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
