# Generated by Django 4.1.7 on 2023-03-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=50)),
                ('rent_amount', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('bond', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=100)),
                ('parking', models.BooleanField(default=False)),
                ('floor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('isRantee', models.BooleanField(default=False)),
                ('isOwner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user'),
        ),
    ]
