CITY = "city"
FLAT_NAME = "flat_name"
FURNISHED = "furnished"
AVG_RATING = "avg_rating"
ADDRESS = "address"
RAMOUNT = "ramount"
AREA = "area"
PROPERTY_TYPE = "property_type"
CHOICES = "choices"
TOTAL_FLATES = "total_flats"
TOTALFLOORS = "totfloors"
FLAT_TYPE = "flat_type"
PARKING = "parking"
STATUS = "status"
AVAILABILITY_DATE = "availability_date"
BOND = "bond"
IS_WISHLIST = "is_wishlist"

PROPERTY_COL = [CITY, FLAT_NAME, FURNISHED, AVG_RATING, ADDRESS, RAMOUNT, AREA, PROPERTY_TYPE,
                CHOICES, TOTAL_FLATES, TOTALFLOORS, FLAT_TYPE, PARKING, STATUS, AVAILABILITY_DATE, BOND, IS_WISHLIST]
MANAGE_RENTAL = [CITY, FLAT_NAME, FURNISHED, AVG_RATING, ADDRESS, RAMOUNT, AREA,
                 PROPERTY_TYPE, CHOICES, TOTAL_FLATES, TOTALFLOORS, FLAT_TYPE, PARKING, STATUS]
