# Generated by Django 4.1.7 on 2023-03-28 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('flat_name', models.CharField(blank=True, max_length=100)),
                ('furnished', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('address', models.CharField(max_length=500)),
                ('ramount', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('choices', models.CharField(max_length=50)),
                ('myImage', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('total_flats', models.IntegerField()),
                ('totfloors', models.IntegerField(blank=True, null=True)),
                ('flat_type', models.CharField(blank=True, max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('status', models.CharField(default='Available', max_length=100)),
                ('availability_date', models.CharField(default=None, max_length=100)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('bond', models.IntegerField(blank=True, null=True)),
                ('is_wishlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.property')),
            ],
        ),
    ]
